use std::error::Error;

pub fn run() -> Result<(), Box<dyn Error>> {
    println!("Hello, client_login_errors!");

    Ok(())
}
